env:
  browser: true
  node: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:security/recommended

plugins:
  - security
  - no-unsanitized

rules:
  no-unused-vars: warn
  no-console: off
