version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # location of your requirements.txt
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "Django"
        versions: ["<4.0.0"]  # Optional: pin minimum version
