
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    restart: unless-stopped
    # command: gunicorn --bind 0.0.0.0:8000 neuroforum_django.wsgi:application

    # command: >
    #   # sh -c "python manage.py collectstatic --noinput &&
    #          daphne -b 0.0.0.0 -p 8000 neuroforum_django.asgi:application"

    command: >
      daphne -b 0.0.0.0 -p 8000 neuroforum_django.asgi:application

    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      DB_HOST: db
      DB_PORT: ${{ secrets.DB_PORT }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # EMAIL_BACKEND: ${EMAIL_BACKEND}
      # EMAIL_HOST: ${EMAIL_HOST}
      # EMAIL_PORT: ${EMAIL_PORT}
      # EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      # EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      # EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      DEBUG: "False"

volumes:
  db_data:

