services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6380:6379"

  web:
    build: .
    restart: unless-stopped

    command: >
      sh -c "python manage.py migrate &&  
        daphne -b 0.0.0.0 -p 8000 neuroforum_django.asgi:application"

    volumes:
      - .:/app:cached
      - ./reports:/app/reports
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
      DEBUG: "False"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8081:8080"
      - "50001:50000"
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  db_data:
  jenkins_home:


