name: Deploy to EC2

on:
  workflow_run:
    workflows: ["CI Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up logs directory for Fail2Ban monitoring
      run: |
          mkdir -p logs
          touch logs/login_failures.log

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: student16
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e
          cd /var/www/neuroforum_django

          git reset --hard
          git clean -fd -e logs/
          git pull origin main

          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" > .env
          echo "FERNET_KEY=${{ secrets.FERNET_KEY }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "SSH_PRIVATE_KEY=\"${{ secrets.SSH_PRIVATE_KEY }}\"" >> .env
          echo "DEBUG=False" >> .env
          echo "RECAPTCHA_PUBLIC_KEY='${{ secrets.RECAPTCHA_PUBLIC_KEY }}'" >> .env
          echo "RECAPTCHA_PRIVATE_KEY='${{ secrets.RECAPTCHA_PRIVATE_KEY }}'" >> .env
          echo "EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend" >> .env
          echo "EMAIL_HOST=smtp.gmail.com" >> .env
          echo "EMAIL_USE_TLS=True" >> .env
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          echo "CI=false" >> .env

          echo "🧹 Cleaning up NeuroForum-related containers and images only..."
          docker-compose down --remove-orphans

          # Prune containers, networks, dangling images
          docker container prune -f || true
          docker image prune -af || true
          docker volume prune -f || true
          docker builder prune -af || true

          docker-compose pull
          docker-compose build

          #  use --no-cache when you're debugging or want a full rebuild
          # docker-compose build --no-cache

          docker-compose up -d --build

          sleep 10

          echo "Running Django migrations inside container..."
          docker-compose exec -T web python manage.py makemigrations --noinput
          docker-compose exec -T web python manage.py migrate --noinput

