name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: student16
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e
          cd /var/www/neuroforum_django

          git reset --hard
          git clean -fd
          git pull origin main

          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" > .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "SSH_PRIVATE_KEY=\"${{ secrets.SSH_PRIVATE_KEY }}\"" >> .env
          echo "DEBUG=False" >> .env
          echo "RECAPTCHA_PUBLIC_KEY='${{ secrets.RECAPTCHA_PUBLIC_KEY }}'" >> .env
          echo "RECAPTCHA_PRIVATE_KEY='${{ secrets.RECAPTCHA_PRIVATE_KEY }}'" >> .env

          docker system prune -af
          docker volume prune -f
          docker builder prune -af

          docker-compose down --remove-orphans
          docker-compose pull
          docker-compose build --no-cache
          docker-compose up -d

          echo "Running Django migrations inside container..."
          docker-compose exec -T web python manage.py makemigrations --noinput
          docker-compose exec -T web python manage.py migrate --noinput

