name: Python Security Checks

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install security tools
        run: |
          pip install safety bandit

      - name: Run Safety (Vulnerability DB Check)
        run: safety scan -r requirements.txt

      - name: Run Bandit (Static Code Analysis)
        run: bandit -r . -ll
