name: Python Static Code Analysis

on: [push, pull_request]

jobs:
  bandit-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit (Static Code Analysis)
        run: bandit -r . -ll
